
server:
  port: 8811

spring:
  application:
    name: lt-cloud-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
    port: 6379
    #password:
    database: 0
    timeout: 60000ms
    jedis:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: -1
        # 最大空闲连接数
        max-idle: 15
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最小空闲连接数
        min-idle: 0


jwt:
  #jwt生成密钥
  secret:
    key: asdfghjkl
  #refreshToken 存储key
  refresh:
    token:
      key:
        format: JWT_REFRESH_TOKEN::%s
  #token黑名单 存储key
  blacklist:
    key:
      format: JWT_BLACKLIST::%s

#token过期时间：1min
token:
  expire:
    time: 60000


  #refreshToken过期时间：2min
refresh:
  token:
    expire:
      time: 120000
